services:
  app:
    build:
      context: ./app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - DB_NAME=TTKTarif
      - DB_PORT=5435

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: TTKTarif
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      PGPORT: 5435
    volumes:
      - db-data:/mnt/docker
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5435:5435"

volumes:
  db-data:
